version: '3.7'

services:
  migrate:
    build: .
    container_name: 'migrate'
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate"
    env_file:
      - .env
    volumes:
      - .:/app
  
  gunicorn:
    image: task-manager_migrate
    container_name: 'gunicorn'
    command: gunicorn -w 4 -b 0.0.0.0:8000 task_manager.wsgi:application
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - migrate
